### PR TITLE
Update project from the template

### LINKED ISSUE #21: Update project structure to the latest template
I'd be happy to send a PR your way after the project gets renamed (https://github.com/sprout42/NamedStruct/issues/10).

### PR DESCRIPTION
**Pull request by jacebrowning**
Closes #21

### CODE REVIEW

**Comment by jacebrowning** [comment]
@sprout42 This should be ready for review/merge. Let me know if you have any question about what something does?

**Comment by sprout42** [comment]
It all looks pretty reasonable.

**Comment by tjdevries** [comment]
We lost the try except that I added in #24, @aaron do you want to just put that back in manually?

**Comment by sprout42** [comment]
whoops, yeah I'll add that back in

**Comment by jacebrowning** [comment]
Sorry about that! I couldn't see any place where `.valid()` could raise an exception and removing didn't seem to affect any test results.

You'll want to add an exception type as well: http://stackoverflow.com/questions/14797375/should-i-always-specify-an-exception-type-in-except-statements

**Comment by sprout42** [comment]
well, it shouldn't raise an exception normally, but it guards against if someone adds a custom type and doesn't properly handle all possible type conditions.

Unfortunately it also means that we don't have a limited set of exceptions to look for, but the `valid()` function is limited enough it should be ok to just have a bare except.

**Comment by sprout42** [comment]
let me see if I can break some to figure out what exceptions to look for.

**Comment by sprout42** [comment]
done, and I removed the try/except guard from elementenum.py and moved it to element.py where it should be.

**Pull request merged**
