### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by tjdevries**
And a few small fixes.

### CODE REVIEW

**Comment by jacebrowning** [comment]
@sprout42 I typically disable these coverage comments and just let Coveralls post the the GitHub status API. Both are on by default.

**Comment by sprout42** [comment]
@jacebrowning I'm not entirely sure how to do that make that change?

**Comment by sprout42** [comment]
wait, I think I got it

**Comment by jacebrowning** [comment]
👍

**Pull request merged**
